// country_enrichment.dart — extra per-country data not in the main VisaCountry model
class CountryEnrichment {
  final bool daytimeRunningLights;
  final String? winterTiresEn;
  final String? winterTiresTr;
  final bool safetyVestRequired;
  final String? foodHighlightsEn;
  final String? foodHighlightsTr;
  final String? streetFoodEn;
  final String? streetFoodTr;
  final String? cityGuideEn;
  final String? cityGuideTr;
  final double? taxFreeMinEur;
  final String? taxFreeCompanies;

  const CountryEnrichment({
    this.daytimeRunningLights = true,
    this.winterTiresEn,
    this.winterTiresTr,
    this.safetyVestRequired = false,
    this.foodHighlightsEn,
    this.foodHighlightsTr,
    this.streetFoodEn,
    this.streetFoodTr,
    this.cityGuideEn,
    this.cityGuideTr,
    this.taxFreeMinEur,
    this.taxFreeCompanies,
  });

  String? winterTires(bool tr) => tr ? winterTiresTr : winterTiresEn;
  String? foodHighlights(bool tr) => tr ? foodHighlightsTr : foodHighlightsEn;
  String? streetFood(bool tr) => tr ? streetFoodTr : streetFoodEn;
  String? cityGuide(bool tr) => tr ? cityGuideTr : cityGuideEn;
}

const Map<String, CountryEnrichment> kCountryEnrichment = {
  'TR': CountryEnrichment(
    daytimeRunningLights: false,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres required Nov–Apr in designated mountain roads. Check with local authorities.',
    winterTiresTr: 'Kasım–Nisan arası belirli dağ yollarında kış lastiği zorunlu. Yerel makamları kontrol edin.',
    foodHighlightsEn: 'Turkish cuisine is one of the world\'s richest: döner, köfte, kebab, lahmacun, menemen, meze spreads, baklava, Turkish delight. Must-try: Iskender kebab in Bursa, balık ekmek by the Bosphorus.',
    foodHighlightsTr: 'Türk mutfağı dünyanın en zenginlerindendir: döner, köfte, kebap, lahmacun, menemen, meze, baklava. Mutlaka: Bursa\'da Iskender kebap, Boğaz\'da balık ekmek.',
    streetFoodEn: 'Simit (sesame bagel), midye dolma (stuffed mussels), kumpir (jacket potato), kokoreç, gözleme, balık ekmek.',
    streetFoodTr: 'Simit, midye dolma, kumpir, kokoreç, gözleme, balık ekmek.',
    cityGuideEn: 'Istanbul: Stay in Sultanahmet (historic) or Beyoğlu/Taksim (modern). Eat in Karaköy, Kadıköy market. Ankara: Kızılay for nightlife, Ulus for history.',
    cityGuideTr: 'İstanbul: Sultanahmet (tarihi) veya Beyoğlu/Taksim (modern). Karaköy ve Kadıköy pazarı. Ankara: Kızılay eğlence, Ulus tarih.',
  ),
  'GR': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres recommended Nov–Mar in northern Greece and mountains. Not legally mandatory nationwide.',
    winterTiresTr: 'Kuzey Yunanistan ve dağlarda Kasım–Mart kış lastiği tavsiye edilir. Ülke genelinde yasal zorunluluk yok.',
    foodHighlightsEn: 'Moussaka, souvlaki, gyros, fresh seafood (grilled octopus, sea bream), spanakopita, horiatiki (Greek salad), loukoumades, baklava. Wash down with ouzo or raki.',
    foodHighlightsTr: 'Musakka, souvlaki, gyros, taze deniz ürünleri (ızgara ahtapot), spanakopita, horiatiki (Yunan salatası), loukoumades, baklava. Ouzo veya rakı ile yıkayın.',
    streetFoodEn: 'Spanakopita (spinach pie), tiropita (cheese pie), koulouri (sesame bread ring), loukoumades (honey doughnuts), souvlaki sticks.',
    streetFoodTr: 'Ispanaklı börek (spanakopita), peynirli börek (tiropita), koulouri, loukoumades, souvlaki.',
    cityGuideEn: 'Athens: Stay in Monastiraki, Kolonaki or Plaka. Eat in Psyrri neighbourhood. Thessaloniki: Ladadika district for tavernas. Santorini: book accommodation months ahead in summer.',
    cityGuideTr: 'Atina: Monastiraki, Kolonaki veya Plaka\'da kalın. Psyrri mahallesinde yiyin. Selanik: Ladadika bölgesi. Santorini: yaz için aylarca önceden rezervasyon yapın.',
    taxFreeMinEur: 50.0,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'BG': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres mandatory Nov 1 – Mar 1 for all vehicles. Minimum tread depth 4mm.',
    winterTiresTr: '1 Kasım – 1 Mart tüm araçlar için kış lastiği zorunlu. Minimum diş derinliği 4mm.',
    foodHighlightsEn: 'Shopska salad (tomatoes, cucumber, white cheese), banitsa (cheese pastry), kavarma (slow-cooked meat stew), tarator (cold yoghurt soup), fresh yoghurt, rakia (fruit brandy).',
    foodHighlightsTr: 'Shopska salatası, banitsa (peynirli börek), kavarma (yavaş pişmiş et güveci), tarator (soğuk yoğurt çorbası), taze yoğurt, rakia.',
    streetFoodEn: 'Banitsa (pastry with cheese or spinach), mekitsi (fried dough), kebapche (grilled minced meat), lyutenitsa sandwiches.',
    streetFoodTr: 'Banitsa, mekitsi, kebapche, lyutenitsa sandviçleri.',
    cityGuideEn: 'Sofia: Stay in city centre near NDK or Vitosha Blvd. Eat in Lozenets. Plovdiv: Old Town guesthouses. Varna: seaside resorts, book summer early.',
    cityGuideTr: 'Sofya: NDK veya Vitoşa Bulvarı yakınında kalın. Lozenets\'te yiyin. Plovdiv: Eski Şehir pansiyonları. Varna: deniz kenarı, yaz için erken rezervasyon.',
    taxFreeMinEur: 50.0,
    taxFreeCompanies: 'Global Blue',
  ),
  'DE': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres required in wintry conditions (snow, ice, slush) — "situational" law. Summer tyres in winter = fine and liability.',
    winterTiresTr: 'Kışlık koşullarda (kar, buz, slush) kış lastiği zorunlu — "durumsal" yasa. Kışın yaz lastiği = ceza ve sorumluluk.',
    foodHighlightsEn: 'Bratwurst, Currywurst, Schnitzel, Sauerbraten, pretzels, Döner (Berlin-style), Black Forest cake, Bavarian pork knuckle. Beer culture is world-famous.',
    foodHighlightsTr: 'Bratwurst, Currywurst, Schnitzel, Sauerbraten, simit (pretzel), Döner (Berlin usulü), Schwarzwälder Kirschtorte, Bavyera domuz inciki. Bira kültürü dünya çapında ünlü.',
    streetFoodEn: 'Currywurst with chips, Döner kebab, pretzels, Bratwurst from market stalls, Leberkäse sandwiches in Bavaria.',
    streetFoodTr: 'Currywurst, Döner, pretzel, Bratwurst, Bavyera\'da Leberkäse sandviçleri.',
    cityGuideEn: 'Berlin: Stay in Mitte, Prenzlauer Berg or Kreuzberg. Munich: Maxvorstadt or Schwabing. Hamburg: Altona. Book hostels for summer festivals. Extensive public transport in all major cities.',
    cityGuideTr: 'Berlin: Mitte, Prenzlauer Berg veya Kreuzberg. Münih: Maxvorstadt. Hamburg: Altona. Yaz festivalleri için önceden rezervasyon yapın.',
    taxFreeMinEur: 50.01,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'FR': CountryEnrichment(
    daytimeRunningLights: false,
    safetyVestRequired: true,
    winterTiresEn: 'Since Nov 2021: winter tyres mandatory in 48 mountain departments Nov–Mar. Rest of France: not mandatory.',
    winterTiresTr: 'Kasım 2021\'den itibaren: 48 dağlık departmanda Kasım–Mart kış lastiği zorunlu. Diğer bölgelerde zorunluluk yok.',
    foodHighlightsEn: 'Croissants, baguettes, coq au vin, boeuf bourguignon, ratatouille, escargot, foie gras, crème brûlée, macarons. Regional cheeses (300+ varieties). Michelin-star dining capital of the world.',
    foodHighlightsTr: 'Kruasan, baget, coq au vin, boeuf bourguignon, ratatouille, salyangoz, foie gras, crème brûlée, makaron. Bölgesel peynirler (300+ çeşit). Dünyanın Michelin yıldızı başkenti.',
    streetFoodEn: 'Crêpes, galettes, jambon-beurre baguettes, socca (Nice), panisse, merguez sausage, falafel (Marais district Paris).',
    streetFoodTr: 'Krep, galette, jambon-beurre baget, socca (Nice), panisse, merguez sosis, falafel (Paris Marais).',
    cityGuideEn: 'Paris: Stay in Marais (4e), Montmartre or Saint-Germain. Eat at Rue Montorgueil market. Lyon: Vieux-Lyon for bouchon restaurants. Nice: Cours Saleya market.',
    cityGuideTr: 'Paris: Marais (4e), Montmartre veya Saint-Germain. Rue Montorgueil pazarında yiyin. Lyon: Vieux-Lyon\'da bouchon restoranlar. Nice: Cours Saleya pazarı.',
    taxFreeMinEur: 100.01,
    taxFreeCompanies: 'Global Blue, Planet, Detaxe.fr',
  ),
  'IT': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres mandatory on many roads Nov 15 – Apr 15 (varies by municipality). Chains must be carried in mountain areas.',
    winterTiresTr: 'Pek çok yolda 15 Kasım – 15 Nisan kış lastiği zorunlu (belediyeye göre değişir). Dağlık bölgelerde zincir bulundurulmalı.',
    foodHighlightsEn: 'Pizza Napoletana, pasta (carbonara, cacio e pepe, amatriciana), risotto, osso buco, gelato, tiramisu, parmigiano reggiano. Each region has distinct cuisine.',
    foodHighlightsTr: 'Napoli pizzası, makarna (carbonara, cacio e pepe, amatriciana), risotto, osso buco, dondurma, tiramisu, parmesan. Her bölgenin kendine özgü mutfağı var.',
    streetFoodEn: 'Supplì (Rome, fried rice balls), arancini (Sicily), panino con lampredotto (Florence), farinata (Genoa), pizza al taglio.',
    streetFoodTr: 'Supplì (Roma, kızarmış pirinç topları), arancini (Sicilya), panino con lampredotto (Floransa), farinata (Cenova), pizza al taglio.',
    cityGuideEn: 'Rome: Stay near Trastevere or Prati. Florence: Oltrarno neighbourhood. Venice: Cannaregio (local) over San Marco (tourist). Milan: Navigli canal district for aperitivo culture.',
    cityGuideTr: 'Roma: Trastevere veya Prati yakını. Floransa: Oltrarno mahallesi. Venedik: San Marco yerine Cannaregio. Milano: aperitivo kültürü için Navigli.',
    taxFreeMinEur: 154.95,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'ES': CountryEnrichment(
    daytimeRunningLights: false,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres not mandatory nationwide. Required in some mountain areas. Always carry chains in Pyrenees.',
    winterTiresTr: 'Ülke genelinde zorunlu değil. Bazı dağlık bölgelerde gerekli. Pireneler\'de her zaman zincir bulundurun.',
    foodHighlightsEn: 'Paella, tapas (jamón ibérico, patatas bravas, gambas al ajillo, tortilla española), gazpacho, churros con chocolate, pintxos in Basque Country.',
    foodHighlightsTr: 'Paella, tapas (jamón ibérico, patatas bravas, gambas al ajillo, tortilla española), gazpacho, churros, Bask Bölgesi\'nde pintxos.',
    streetFoodEn: 'Churros, bocadillo de jamón, empanadas, croquetas, buñuelos.',
    streetFoodTr: 'Churros, jamón sandviç, empanada, kroket, buñuelos.',
    cityGuideEn: 'Madrid: Stay in Malasaña or Lavapiés. Eat at Mercado de San Miguel. Barcelona: Gràcia or Eixample. San Sebastián: Parte Vieja for world-class pintxos bars.',
    cityGuideTr: 'Madrid: Malasaña veya Lavapiés. Mercado de San Miguel\'de yiyin. Barselona: Gràcia veya Eixample. San Sebastián: dünya kalitesinde pintxos barları.',
    taxFreeMinEur: 90.16,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'HR': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres mandatory Nov 15 – Apr 15. Minimum tread depth 4mm.',
    winterTiresTr: '15 Kasım – 15 Nisan kış lastiği zorunlu. Minimum diş derinliği 4mm.',
    foodHighlightsEn: 'Peka (lamb/vegetables under a bell), Pašticada (Dalmatian beef stew), Crni rižot (black risotto), fresh Adriatic seafood, truffles from Istria, Pag cheese.',
    foodHighlightsTr: 'Peka (çan altında kuzu/sebze), Pašticada (Dalmaçya sığır güveci), Crni rižot (siyah risotto), taze Adriyatik deniz ürünleri, İstriya mantarı, Pag peyniri.',
    streetFoodEn: 'Burek (pastry with meat/cheese), ćevapčići, roštilj (grilled meats), grilled fish with olive oil and lemon.',
    streetFoodTr: 'Börek, ćevapčići, ızgara etler, zeytinyağı ve limonlu ızgara balık.',
    cityGuideEn: 'Dubrovnik: Old Town is magical but pricey; stay in Lapad for value. Split: Diocletian\'s Palace area. Zadar: great food scene, fewer tourists. Book summer well in advance — Croatia is very popular.',
    cityGuideTr: 'Dubrovnik: Eski Şehir büyüleyici ama pahalı; bütçe için Lapad\'da kalın. Split: Diocletian Sarayı çevresi. Zadar: harika yemek, daha az turist. Yaz için erkenden rezervasyon yapın.',
    taxFreeMinEur: 74.99,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'AT': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres mandatory Nov 1 – Apr 15 in winter conditions. Year-round if all-season tyres labelled M+S.',
    winterTiresTr: 'Kış koşullarında 1 Kasım – 15 Nisan kış lastiği zorunlu. M+S etiketli 4 mevsim lastik yıl boyunca geçerli.',
    foodHighlightsEn: 'Wiener Schnitzel, Tafelspitz (boiled beef), Apfelstrudel, Sachertorte, Kaiserschmarrn, Leberkäse, Käsekrainer sausage. Vienna coffee house culture is UNESCO-listed.',
    foodHighlightsTr: 'Viyana Şnitzel, Tafelspitz, Elmalı Strudel, Sachertorte, Kaiserschmarrn, Leberkäse, Käsekrainer. Viyana kahvehane kültürü UNESCO listesinde.',
    streetFoodEn: 'Käsekrainer (cheese sausage) from street stands, Leberkäse roll, Strudel from bakeries.',
    streetFoodTr: 'Sokak tezgahlarından Käsekrainer, Leberkäse ekmek arası, pastanelerden Strudel.',
    cityGuideEn: 'Vienna: Stay in 7th (Neubau) or 8th (Josefstadt) districts. Eat at Naschmarkt. Salzburg: Old Town guesthouses. Innsbruck: base for Alps skiing. Vignette required for motorways.',
    cityGuideTr: 'Viyana: 7. (Neubau) veya 8. (Josefstadt) ilçelerde kalın. Naschmarkt\'ta yiyin. Salzburg: Eski Şehir pansiyonları. Innsbruck: Alp kayağı üssü. Otoyollar için vinyet gerekli.',
    taxFreeMinEur: 75.01,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'CH': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: false,
    winterTiresEn: 'Winter tyres not legally mandatory but practically essential Oct–Apr in Alps. Chains required in many mountain passes.',
    winterTiresTr: 'Yasal zorunluluk yok ancak Alpler\'de Ekim–Nisan pratikte zorunlu. Pek çok dağ geçidinde zincir şart.',
    foodHighlightsEn: 'Fondue (cheese or chocolate), raclette, Rösti (potato dish), Zürcher Geschnetzeltes (veal in cream), Bircher muesli, Swiss chocolate, Toblerone. Prices are very high.',
    foodHighlightsTr: 'Fondue (peynir veya çikolata), raclette, Rösti (patates yemeği), Zürcher Geschnetzeltes, Bircher müsli, İsviçre çikolatası, Toblerone. Fiyatlar çok yüksek.',
    streetFoodEn: 'Bratwurst from street stalls in Zurich, pretzels, rösti sandwiches.',
    streetFoodTr: 'Zürih\'te sokak tezgahlarından Bratwurst, pretzel, rösti sandviçleri.',
    cityGuideEn: 'Zurich: Stay in Langstrasse or Wiedikon. Geneva: Carouge neighbourhood. Lucerne: great for day trips, lake views. Interlaken: base for Jungfrau adventures. Swiss vignette (40 CHF/year) required on motorways.',
    cityGuideTr: 'Zürih: Langstrasse veya Wiedikon. Cenevre: Carouge mahallesi. Luzern: gün gezisi için ideal. Interlaken: Jungfrau macerası üssü. Otoyollar için İsviçre vigneti (40 CHF/yıl) zorunlu.',
    taxFreeMinEur: 300.0,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'NL': CountryEnrichment(
    daytimeRunningLights: false,
    safetyVestRequired: false,
    winterTiresEn: 'Winter tyres not mandatory. Rarely needed due to mild coastal climate, but recommended for cold snaps.',
    winterTiresTr: 'Kış lastiği zorunlu değil. Ilıman iklim nedeniyle nadiren gerekir, soğuk dalgalar için tavsiye edilir.',
    foodHighlightsEn: 'Stroopwafels, Dutch cheese (Gouda, Edam), herring (haring) with onions, bitterballen, poffertjes, stamppot, Dutch pancakes (pannenkoeken).',
    foodHighlightsTr: 'Stroopwafel, Hollanda peyniri (Gouda, Edam), soğanlı ringa balığı, bitterballen, poffertjes, stamppot, Hollanda pankekleri.',
    streetFoodEn: 'Haring from fish stalls, stroopwafels, raw herring with onions, frites met mayo (chips with mayo), poffertjes.',
    streetFoodTr: 'Balık tezgahlarından haring, stroopwafel, soğanlı çiğ ringa, mayonezli patates kızartması, poffertjes.',
    cityGuideEn: 'Amsterdam: Stay in Jordaan or De Pijp. Eat at Albert Cuyp Market. Rotterdam: Markthal food hall, modern architecture. The Hague: international city feel, less touristy than Amsterdam.',
    cityGuideTr: 'Amsterdam: Jordaan veya De Pijp\'te kalın. Albert Cuyp Pazarı\'nda yiyin. Rotterdam: Markthal, modern mimari. Lahey: Amsterdam\'dan daha az turistik.',
    taxFreeMinEur: 50.01,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'BE': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres not legally mandatory but strongly recommended Nov–Feb. Snow chains required on marked mountain roads.',
    winterTiresTr: 'Yasal zorunluluk yok ancak Kasım–Şubat arası kış lastiği şiddetle önerilir.',
    foodHighlightsEn: 'Belgian waffles (Brussels liège style), moules-frites, Belgian chocolate, frites (chips), beef stew with beer (carbonnade), speculoos cookies, over 1,500 beer varieties.',
    foodHighlightsTr: 'Belçika waffle (Brüksel ve Liège usulü), midye-patates, Belçika çikolatası, patates kızartması, bira ile biftek güveci, speculoos kurabiye, 1500+ bira çeşidi.',
    streetFoodEn: 'Gaufres (waffles), frites from friteries, waffles with toppings, boulet liégeois (meatballs).',
    streetFoodTr: 'Gaufres (waffle), friteri tezgahlarından patates, toppingli waffle, Liège usulü köfte.',
    cityGuideEn: 'Brussels: Stay in Ixelles/Ste-Catherine. Bruges: book months ahead — extremely popular. Ghent: Patershol neighbourhood. Antwerp: fashion district and diamond quarter.',
    cityGuideTr: 'Brüksel: Ixelles/Ste-Catherine. Brugge: aylarca önceden rezervasyon. Ghent: Patershol mahallesi. Antwerp: moda bölgesi ve elmas çeyreği.',
    taxFreeMinEur: 125.01,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'PL': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: false,
    winterTiresEn: 'Winter tyres not legally mandatory but strongly recommended Dec–Mar. Snow chains advisable in mountains.',
    winterTiresTr: 'Yasal zorunluluk yok ancak Aralık–Mart arası şiddetle önerilir. Dağlarda zincir tavsiye edilir.',
    foodHighlightsEn: 'Pierogi (dumplings), bigos (hunter\'s stew), żurek (sour rye soup), kielbasa, barszcz (beetroot soup), kotlet schabowy (pork schnitzel), paczki (doughnuts).',
    foodHighlightsTr: 'Pierogi (mantı), bigos (avcı güveci), żurek (ekşi çavdar çorbası), kielbasa, barszcz (pancar çorbası), kotlet schabowy, paczki (çörek).',
    streetFoodEn: 'Zapiekanka (open-faced mushroom baguette), kielbasa from market stalls, paczki, obwarzanek (bagel rings in Krakow).',
    streetFoodTr: 'Zapiekanka, tezgahlardan kielbasa, paczki, Kraków\'da obwarzanek (simit).',
    cityGuideEn: 'Krakow: Old Town and Kazimierz district are unmissable. Warsaw: Praga district is emerging. Gdansk: amber coast city. Poland is budget-friendly by EU standards.',
    cityGuideTr: 'Kraków: Eski Şehir ve Kazimierz çeyreği vazgeçilmez. Varşova: Praga bölgesi yükselen trend. Gdansk: amber sahili şehri. Polonya AB içinde bütçe dostu.',
    taxFreeMinEur: 50.0,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'CZ': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres mandatory in wintry conditions (snow, ice, slush). Minimum tread 4mm.',
    winterTiresTr: 'Kışlık koşullarda (kar, buz, slush) kış lastiği zorunlu. Minimum diş 4mm.',
    foodHighlightsEn: 'Svíčková (beef sirloin in cream sauce), vepřo-knedlo-zelo (pork, dumplings, sauerkraut), goulash, trdelník (chimney cake), pork ribs. Czech beer is world-famous.',
    foodHighlightsTr: 'Svíčková (krema soslu sığır filetosu), vepřo-knedlo-zelo, gulyas, trdelník, domuz kaburga. Çek birası dünya çapında ünlü.',
    streetFoodEn: 'Trdelník (chimney cake — touristy but tasty), smažený sýr (fried cheese sandwich), langos, klobásy (sausage).',
    streetFoodTr: 'Trdelník, smažený sýr (kızarmış peynir sandviç), langos, klobásy (sosis).',
    cityGuideEn: 'Prague: Vinohrady or Žižkov for local feel vs tourist Old Town. Brno: university city, cheaper. Cesky Krumlov: day trip from Prague. Book Prague months ahead in summer.',
    cityGuideTr: 'Prag: yerel atmosfer için Vinohrady veya Žižkov. Brno: üniversite şehri, daha ucuz. Cesky Krumlov: Prag\'dan gün gezisi. Yaz için aylarca önceden rezervasyon.',
    taxFreeMinEur: 174.0,
    taxFreeCompanies: 'Global Blue',
  ),
  'HU': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres not legally mandatory. Recommended Nov–Mar. Snow chains advisable in highlands.',
    winterTiresTr: 'Yasal zorunluluk yok. Kasım–Mart tavsiye edilir. Yaylalarda zincir önerilir.',
    foodHighlightsEn: 'Goulash (gulyás), chicken paprikash, lángos (fried dough), kürtőskalács (chimney cake), fisherman\'s soup (halászlé), stuffed peppers. Pálinka fruit brandy.',
    foodHighlightsTr: 'Gulyás, csirke paprikás, lángos, kürtőskalács, halászlé (balıkçı çorbası), dolgulu biber. Pálinka meyve rakısı.',
    streetFoodEn: 'Lángos (fried dough with sour cream and cheese), kürtőskalács, kolbász (sausage), kürtőskalács.',
    streetFoodTr: 'Lángos (ekşi krema ve peynirli kızarmış hamur), kürtőskalács, kolbász.',
    cityGuideEn: 'Budapest: Pest side for nightlife (ruin bars), Buda for castle. District 7 (Jewish Quarter) is the centre of action. Balaton lake for summer. E-vignette required for Hungarian motorways.',
    cityGuideTr: 'Budapeşte: Pest yakası gece hayatı (harabeye dönmüş barlar), Buda kale için. 7. bölge (Yahudi Mahallesi) merkez. Balaton gölü yaz için. Macar otoyolları için e-vinyet gerekli.',
    taxFreeMinEur: 175.0,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
  'RO': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres mandatory Nov 1 – Mar 31. Minimum tread 1.6mm. Fine for non-compliance.',
    winterTiresTr: '1 Kasım – 31 Mart kış lastiği zorunlu. Minimum diş 1.6mm. Uymayanlara ceza.',
    foodHighlightsEn: 'Mici (grilled minced meat rolls), sarmale (stuffed cabbage), ciorbă (sour soup), mămăligă (polenta), cozonac (sweet bread), palinca (plum brandy).',
    foodHighlightsTr: 'Mici (ızgara köfte), sarmale (lahana sarması), ciorbă (ekşi çorba), mămăligă (polenta), cozonac, palinca (erik rakısı).',
    streetFoodEn: 'Mici from street grills, covrigi (pretzels), papanași (fried doughnuts with jam).',
    streetFoodTr: 'Sokak ızgaralarından mici, covrigi (simit), papanași.',
    cityGuideEn: 'Bucharest: Old Town (Centrul Vechi) for nightlife. Brasov: Transylvania gateway. Cluj-Napoca: vibrant university city. Sibiu: beautifully preserved medieval centre. Road quality varies widely.',
    cityGuideTr: 'Bükreş: gece hayatı için Eski Şehir. Brașov: Transilvanya kapısı. Cluj-Napoca: canlı üniversite şehri. Sibiu: güzel korunmuş ortaçağ merkezi. Yol kalitesi çok değişken.',
    taxFreeMinEur: 175.0,
    taxFreeCompanies: 'Global Blue',
  ),
  'PT': CountryEnrichment(
    daytimeRunningLights: true,
    safetyVestRequired: true,
    winterTiresEn: 'Winter tyres not mandatory. Snow chains required on some mountain roads in winter.',
    winterTiresTr: 'Zorunlu değil. Kışın bazı dağ yollarında kar zinciri gerekli.',
    foodHighlightsEn: 'Pastel de nata (custard tart), bacalhau (salt cod — 365 ways to cook it), piri-piri chicken, caldo verde (kale soup), francesinha (Porto sandwich), seafood cataplana.',
    foodHighlightsTr: 'Pastel de nata (muhallebili tart), bacalhau (tuzlu morina — 365 pişirme yöntemi), piri-piri tavuk, caldo verde, francesinha (Porto sandviç), meyve denizi cataplana.',
    streetFoodEn: 'Pastel de nata, bifanas (pork sandwich), prego (steak sandwich), caracóis (snails in summer), grilled sardines.',
    streetFoodTr: 'Pastel de nata, bifanas (domuz sandviç), prego (biftek sandviç), caracóis, ızgara sardalye.',
    cityGuideEn: 'Lisbon: Alfama, Mouraria and Bairro Alto for authentic feel. Porto: Ribeira waterfront, Foz district. Algarve: book summer months ahead. Portugal is still relatively good value vs W. Europe.',
    cityGuideTr: 'Lizbon: Alfama, Mouraria ve Bairro Alto. Porto: Ribeira rıhtımı, Foz. Algarve: yaz için aylarca önceden. Portekiz Batı Avrupa\'ya göre hâlâ makul fiyatlı.',
    taxFreeMinEur: 61.35,
    taxFreeCompanies: 'Global Blue, Planet',
  ),
};

CountryEnrichment? enrichmentFor(String code) => kCountryEnrichment[code];
