import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'features/notifications/providers/notification_coordinator_provider.dart';

// AppLocalizations is generated by flutter gen-l10n (l10n.yaml).
// Uncomment the import and delegates below once gen-l10n output is committed.
// import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class VisaRadarApp extends ConsumerWidget {
  const VisaRadarApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Warm the notification coordinator so it begins listening to state changes.
    ref.watch(notificationCoordinatorProvider);

    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: 'VisaRadar',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      // Localizations: re-enable AppLocalizations delegates once gen-l10n output is committed.
      // localizationsDelegates: AppLocalizations.localizationsDelegates,
      // supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('tr'),
      ],
      routerConfig: router,
    );
  }
}
